apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # GF_PROMETHEUS_URL được set qua environment variable
    # Local Docker:   http://prometheus:9090
    # Render:         https://your-prometheus.onrender.com
    url: ${GF_PROMETHEUS_URL}
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: '15s'
