name: Crawl XSMN

on:
  schedule:
    - cron: '0 10 * * *'  # 16h VN
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install puppeteer

      - run: node crawler/crawl.js
